"""
Django settings for food_recommender project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = True  # Or use an environment variable for safety

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*&1ho75=js2y3r$w4^)gz9o%irsbbx^joo(e#%4o$=4fv(7%&_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['food-recommender-vqtg.onrender.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'food_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'food_recommender.urls'
STATIC_URL = '/static/'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'food_recommender.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
        'default': dj_database_url.parse(postgres://bindu_3zng_user:PFxu2jtRsp6hBaha2PpHSzJD0RrJqJqP@dpg-d06as0ruibrs73ed7e30-a/bindu_3zng, conn_max_age=600),
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Define 70 selected features (adjust if you have specific columns)
SELECTED_FEATURES = [
    '25-OH-D3 [ug]', '?-Cryptoxanthin [ug]', 'Alanine [g]', 'Aluminium (Al) [mg]', 'Apigenin [mg]',
    'Apigenin-7-O-neohesperidoside [mg]', 'Arachidic (C20:0) [mg]', 'Arginine [g]', 'Arsenic (As) [ug]',
    'Behenic (C22:0) [mg]', 'Cadmium (Cd) [mg]', 'Carbs', 'Cholesterol [mg]', 'Cobalt (Co) [mg]',
    'Docosa pentaenoic (C22:5n3) [mg]', 'Eicosaenoic (C20:1n9) [mg]', 'Eicosatrienoic (C20:3n6) [mg]',
    'Energy [kJ]', 'Fumaric Acid [mg]', 'Gallic acid [mg]', 'Glucose [g]', 'Glutamic Acid [g]',
    'Glycine [g]', 'Histidine [g]', 'Iron (Fe) [mg]', 'Isoleucine [g]', 'Lauric (C12:0) [mg]',
    'Lead (Pb) [mg]', 'Linoleic (C18:2n6) [%]', 'Linoleic (C18:2n6) [mg]', 'Lithium (Li) [mg]',
    'Malic Acid [mg]', 'Manganese (Mn) [mg]', 'Menaquinones (K2) [ug]', 'Mercury (Hg) [ug]',
    'Methionine [g]', 'Moisture [g]', 'Molybdenum (Mo) [mg]', 'Myristic (C14:0) [mg]',
    'Nervonic (C24:1n9) [mg]', 'Nickel (Ni) [mg]', 'Oligosaccharides - Raffinose [g]',
    'Oxalate-Soluble [mg]', 'Palmitic (C16:0) [%]', 'Palmitic (C16:0) [mg]', 'Palmitoleic (C16:1) [%]',
    'Pantothenic Acid (B5) [mg]', 'Pentadecanoic (C15:0) [mg]', 'Phenylalanine [g]',
    'Phophorus (P) [mg]', 'Phytosterols - Campesterol [mg]', 'Proteins', 'Protocatechuic acid [mg]',
    'Quercetin-3-O-rutinoside [mg]', 'Retinol [ug]', 'Riboflavin (B2) [mg]', 'Sucrose [g]',
    'Thiamine(B1) [mg]', 'Threonine [g]', 'Tocopherols (Alpha) [mg]', 'Tocopherols (Beta) [mg]',
    'Tocotrienols (Beta) [mg]', 'Total Available CHO [g]', 'Total Carotenoids [ug]',
    'Total Folates (B9) [ug]', 'Total Poly Unsaturated Fatty Acids (TPUFA) [mg]',
    'Total Saturated Fatty Acids (TSFA) [mg]', 'Total Starch [g]', 'Tryptophan [g]', 'Zinc (Zn) [mg]'
]
