# Generated by Django 4.2.1 on 2025-04-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
