# Generated by Django 4.2.1 on 2025-04-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_alter_fooditem_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
