# Generated by Django 4.2.1 on 2025-04-24 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_alter_fooditem_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationhistory',
            name='recommended_food_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended1', to='food_app.fooditem'),
        ),
        migrations.AlterField(
            model_name='recommendationhistory',
            name='recommended_food_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended2', to='food_app.fooditem'),
        ),
        migrations.AlterField(
            model_name='recommendationhistory',
            name='recommended_food_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended3', to='food_app.fooditem'),
        ),
        migrations.AlterField(
            model_name='recommendationhistory',
            name='selected_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.fooditem'),
        ),
    ]
