# Generated by Django 4.2.1 on 2025-04-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_alter_recommendationhistory_recommended_food_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationhistory',
            name='rating_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='rating_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='rating_3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
