# Generated by Django 4.2.1 on 2025-04-24 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_recommendationhistory_rating_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField()),
                ('set_number', models.PositiveSmallIntegerField(default=1)),
                ('rating_1', models.FloatField(blank=True, null=True)),
                ('rating_2', models.FloatField(blank=True, null=True)),
                ('rating_3', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='food_app.recommendationhistory')),
                ('recommended_food_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='food_app.fooditem')),
                ('recommended_food_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='food_app.fooditem')),
                ('recommended_food_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='food_app.fooditem')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
    ]
