# Generated by Django 5.2 on 2025-04-25 01:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food_app", "0006_recommendationset"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecommendationSet",
        ),
    ]
