from django.db import models
from django.contrib.auth.models import User

class FoodItem(models.Model):
    code = models.CharField(max_length=10, unique=True)
    food_name = models.CharField(max_length=255)
    food_group = models.CharField(max_length=100)
    doh25 = models.FloatField(null=True, blank=True)
    crypxb = models.FloatField(null=True, blank=True)
    ala = models.FloatField(null=True, blank=True)
    al = models.FloatField(null=True, blank=True)
    apigen = models.FloatField(null=True, blank=True)
    apigen7onshps = models.FloatField(null=True, blank=True)
    f20d0 = models.FloatField(null=True, blank=True)
    arg = models.FloatField(null=True, blank=True)
    as_1 = models.FloatField(null=True, blank=True)
    f22d0 = models.FloatField(null=True, blank=True)
    cd = models.FloatField(null=True, blank=True)
    carbs = models.FloatField(null=True, blank=True)
    cholc = models.FloatField(null=True, blank=True)
    co = models.FloatField(null=True, blank=True)
    f22d5n3 = models.FloatField(null=True, blank=True)
    f20d1_n9f = models.FloatField(null=True, blank=True)
    f20d3n6 = models.FloatField(null=True, blank=True)
    enerc = models.FloatField(null=True, blank=True)
    fumac = models.FloatField(null=True, blank=True)
    gallac = models.FloatField(null=True, blank=True)
    glus = models.FloatField(null=True, blank=True)
    glu = models.FloatField(null=True, blank=True)
    gly = models.FloatField(null=True, blank=True)
    his = models.FloatField(null=True, blank=True)
    fe = models.FloatField(null=True, blank=True)
    ile = models.FloatField(null=True, blank=True)
    f12d0 = models.FloatField(null=True, blank=True)
    pb = models.FloatField(null=True, blank=True)
    tf18d2cn6 = models.FloatField(null=True, blank=True)
    f18d2cn6 = models.FloatField(null=True, blank=True)
    li = models.FloatField(null=True, blank=True)
    malac = models.FloatField(null=True, blank=True)
    mn = models.FloatField(null=True, blank=True)
    vitk2 = models.FloatField(null=True, blank=True)
    hg = models.FloatField(null=True, blank=True)
    met = models.FloatField(null=True, blank=True)
    water = models.FloatField(null=True, blank=True)
    mo = models.FloatField(null=True, blank=True)
    f14d0 = models.FloatField(null=True, blank=True)
    f24d1_c = models.FloatField(null=True, blank=True)
    ni = models.FloatField(null=True, blank=True)
    rafs = models.FloatField(null=True, blank=True)
    oxals = models.FloatField(null=True, blank=True)
    tf16d0 = models.FloatField(null=True, blank=True)
    f16d0 = models.FloatField(null=True, blank=True)
    tf16d1c = models.FloatField(null=True, blank=True)
    pantac = models.FloatField(null=True, blank=True)
    f15d0 = models.FloatField(null=True, blank=True)
    phe = models.FloatField(null=True, blank=True)
    p = models.FloatField(null=True, blank=True)
    camt = models.FloatField(null=True, blank=True)
    proteins = models.FloatField(null=True, blank=True)
    pcathac = models.FloatField(null=True, blank=True)
    querce3ortns = models.FloatField(null=True, blank=True)
    retol = models.FloatField(null=True, blank=True)
    ribf = models.FloatField(null=True, blank=True)
    sucs = models.FloatField(null=True, blank=True)
    thia = models.FloatField(null=True, blank=True)
    thr = models.FloatField(null=True, blank=True)
    tocpha = models.FloatField(null=True, blank=True)
    tocphb = models.FloatField(null=True, blank=True)
    toctrb = models.FloatField(null=True, blank=True)
    cho = models.FloatField(null=True, blank=True)
    cartoid = models.FloatField(null=True, blank=True)
    folsum = models.FloatField(null=True, blank=True)
    fapu = models.FloatField(null=True, blank=True)
    fasat = models.FloatField(null=True, blank=True)
    starch = models.FloatField(null=True, blank=True)
    trp = models.FloatField(null=True, blank=True)
    zn = models.FloatField(null=True, blank=True)
    estimated_price = models.FloatField(null=True, blank=True)

    def __str__(self):
        return self.food_name


# RecommendationHistory models
class RecommendationHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    selected_food = models.ForeignKey(FoodItem, on_delete=models.CASCADE)
    recommended_food_1 = models.ForeignKey(FoodItem, on_delete=models.SET_NULL, null=True, related_name='recommended1')
    recommended_food_2 = models.ForeignKey(FoodItem, on_delete=models.SET_NULL, null=True, related_name='recommended2')
    recommended_food_3 = models.ForeignKey(FoodItem, on_delete=models.SET_NULL, null=True, related_name='recommended3')
    created_at = models.DateTimeField(auto_now_add=True)
    rating_1 = models.FloatField(null=True, blank=True)     #Ratings
    rating_2 = models.FloatField(null=True, blank=True)
    rating_3 = models.FloatField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"{self.user.username} - {self.selected_food.food_name}"

